/*
 * This file was generated by the Gradle 'init' task.
 */

import org.gradle.accessors.dm.LibrariesForLibs
import org.gradle.api.Project
import org.gradle.kotlin.dsl.getByType

private val Project.libs: LibrariesForLibs
    get() = extensions.getByType()

plugins {
    id("buildlogic.java-library-conventions")
    id("buildlogic.spring-boot-common-conventions")
}

